/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbookRouteImport } from './routes/ebook'
import { Route as DiaNRouteImport } from './routes/dia.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookRoute = EbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaNRoute = DiaNRouteImport.update({
  id: '/dia/$n',
  path: '/dia/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ebook': typeof EbookRoute
  '/dia/$n': typeof DiaNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ebook': typeof EbookRoute
  '/dia/$n': typeof DiaNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ebook': typeof EbookRoute
  '/dia/$n': typeof DiaNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ebook' | '/dia/$n'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ebook' | '/dia/$n'
  id: '__root__' | '/' | '/ebook' | '/dia/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EbookRoute: typeof EbookRoute
  DiaNRoute: typeof DiaNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook': {
      id: '/ebook'
      path: '/ebook'
      fullPath: '/ebook'
      preLoaderRoute: typeof EbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia/$n': {
      id: '/dia/$n'
      path: '/dia/$n'
      fullPath: '/dia/$n'
      preLoaderRoute: typeof DiaNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EbookRoute: EbookRoute,
  DiaNRoute: DiaNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
